#! /bin/bash
export EDITOR=nvim

source <(fzf --zsh)
source <(zoxide init zsh --cmd cd)
source <(starship init zsh)
# Variables
PROJECT_PATH_PYTHON="/home/maverikio/projects/"
PROJECT_PATH_LUA="/home/maverikio/projects/lua"
PROJECT_PATH_RUST="/home/maverikio/projects/rust"
PROJECT_PATH_PYTHON_SCRIPTS="/home/maverikio/projects/scripts"

eval "$(proj-cmd init zsh)"

mav() {
  macchina --theme maverikio -o host -o machine -o processor -o distribution -o processor-load -o battery
}

index() {
  if [[ "$1" == "" ]]; then
    dir=$(pwd)
  else
    dir=$1
  fi
  echo "Opening $dir/indexer.json in nvim..."
  nvim $dir/indexer.json
}

config() {
  nvim /home/maverikio/.config/$1
}

clean() {
  files="$(find /home/maverikio/projects/rust -type d -name target*)"
  if [[ "$files" == "" ]]; then
    echo "nothing to clean"
  else
    echo $files
    read "REPLY?Delete shown directories? (y/N): "
    if [[ "$REPLY" == "y" ]]; then
      echo "deleting..."
      find /home/maverikio/projects/rust/ -type d -name target\* -exec rm -fr {} ';' 1>/dev/null
    fi
  fi

}

# Aliases

alias alaconfigg="$PROJECT_PATH_PYTHON_SCRIPTS/alaconfig.py"
alias love="/Applications/love.app/Contents/MacOS/love"
alias zel="zellij -l welcome"
alias clear="clear; mav"
alias pip="python3 -m pip"
alias ls="eza"
alias indexer="python3 /home/maverikio/projects/python/Indexer/main.py"

alias gc="git commit"
alias gp="git push -u origin main"
alias gac="git add . && git commit"
alias gacp="git add . && git commit && git push -u origin main"
